[package]
name = "hl7v2-guard"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "ML-based anomaly detection for HL7 messages."
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hl7v2 = { version = "1.2.1", path = "../hl7v2", default-features = false, features = ["experimental-guard"] }
