warn-on-all-pedantic = true

allowed-lints = [
    "clippy::missing_errors_doc",
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
    "clippy::similar_names",
    "clippy::too_many_lines",
]
