ignore:
  - "**/*.md"
  - "**/Cargo.toml"
  - "**/build.rs"
  - "**/src/tests.rs"
  - "**/tests/**"
  - ".github/**"
  - ".spectral.yml"
  - "api/**"
  - "buf.gen.yaml"
  - "Cargo.lock"
  - "Cargo.toml"
  - "clippy.toml"
  - "codecov.yml"
  - "config.example.toml"
  - "docs/**"
  - "policy/**"
  - "profiles/**"
  - "schemas/**"
  - "xtask/**"
