[package]
readme = "README.md"
name = "hl7v2-network"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "HL7 v2 MLLP network client and server (TCP/TLS)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories = ["network-programming", "asynchronous"]

[dependencies]
hl7v2 = { version = "1.2.1", path = "../hl7v2", default-features = false, features = [
    "network",
] }

[features]
default = []
tls = []

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util"] }
tokio-util = { workspace = true, features = ["codec"] }
bytes = { workspace = true }
