//! gRPC service implementation for HL7v2.

use crate::models::{
    RedactionAction as ServerRedactionAction,
    RedactionActionReceipt as ServerRedactionActionReceipt,
    RedactionActionStatus as ServerRedactionActionStatus,
    RedactionReceipt as ServerRedactionReceipt,
};
use crate::redaction::redact_message;
use crate::server::AppState;
use hl7v2::{
    Comp as RustComp, Field as RustField, Message as RustMessage, Rep as RustRep,
    Segment as RustSegment, parse as rust_parse,
};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::Arc;
use tonic::{Request, Response, Status};

// Include the generated gRPC code
/// Generated gRPC protocol code (protobuf messages and service traits).
#[expect(
    missing_docs,
    reason = "protobuf bindings are generated by tonic/prost"
)]
pub mod proto {
    tonic::include_proto!("hl7v2.v1");
}

use proto::hl7_service_server::Hl7Service;
use proto::*;

/// Implementation of the HL7Service gRPC trait
pub struct Hl7ServiceImpl {
    #[expect(
        dead_code,
        reason = "service state is retained for runtime parity and future streaming support"
    )]
    state: Arc<AppState>,
}

impl Hl7ServiceImpl {
    /// Create a new gRPC service instance
    pub fn new(state: Arc<AppState>) -> Self {
        Self { state }
    }
}

#[tonic::async_trait]
impl Hl7Service for Hl7ServiceImpl {
    async fn parse(
        &self,
        request: Request<ParseRequest>,
    ) -> Result<Response<ParseResponse>, Status> {
        let req = request.into_inner();
        Ok(Response::new(parse_grpc_message_response(
            &req.message,
            req.mllp_framed,
        )))
    }

    type ParseStreamStream =
        tokio_stream::wrappers::ReceiverStream<Result<ParseStreamResponse, Status>>;

    async fn parse_stream(
        &self,
        request: Request<tonic::Streaming<ParseStreamRequest>>,
    ) -> Result<Response<Self::ParseStreamStream>, Status> {
        let mut stream = request.into_inner();
        let (sender, receiver) = tokio::sync::mpsc::channel(8);

        tokio::spawn(async move {
            loop {
                match stream.message().await {
                    Ok(Some(request)) => {
                        let response = parse_stream_response_from_parse_response(
                            parse_grpc_message_response(&request.message, request.mllp_framed),
                        );
                        if sender.send(Ok(response)).await.is_err() {
                            break;
                        }
                    }
                    Ok(None) => break,
                    Err(status) => {
                        if sender.send(Err(status)).await.is_err() {
                            break;
                        }
                        break;
                    }
                }
            }
        });

        Ok(Response::new(tokio_stream::wrappers::ReceiverStream::new(
            receiver,
        )))
    }

    async fn validate(
        &self,
        request: Request<ValidateRequest>,
    ) -> Result<Response<ValidateResponse>, Status> {
        let req = request.into_inner();

        let message_bytes = if req.mllp_framed {
            hl7v2::unwrap_mllp(&req.message)
                .map_err(|e| Status::invalid_argument(format!("Failed to unwrap MLLP: {}", e)))?
        } else {
            req.message.as_slice()
        };

        let message = rust_parse(message_bytes)
            .map_err(|e| Status::invalid_argument(format!("Failed to parse HL7: {}", e)))?;

        let profile = hl7v2::load_profile(&req.profile)
            .map_err(|_error| Status::invalid_argument(crate::PROFILE_LOAD_SAFE_MESSAGE))?;

        let issues = hl7v2::validate(&message, &profile);
        let report = hl7v2::ValidationReport::from_issues(
            &message,
            Some(profile.message_structure.clone()),
            issues.clone(),
        );
        let valid = report.valid;

        let mut errors = Vec::new();
        let mut warnings = Vec::new();

        for issue in issues {
            let location = issue.path.map(|p| {
                let mut loc = Location::default();
                let parts: Vec<&str> = p.split('.').collect();
                if !parts.is_empty() {
                    loc.segment = parts[0].to_string();
                }
                if parts.len() > 1 {
                    loc.field = parts[1].parse().unwrap_or(0);
                }
                if parts.len() > 2 {
                    loc.component = parts[2].parse().unwrap_or(0);
                }
                loc
            });

            let proto_issue = ValidationIssue {
                code: issue.code,
                message: issue.detail,
                severity: match issue.severity {
                    hl7v2::Severity::Error => validation_issue::Severity::Error as i32,
                    hl7v2::Severity::Warning => validation_issue::Severity::Warning as i32,
                },
                location,
                advice: String::new(),
            };

            if issue.severity == hl7v2::Severity::Error {
                errors.push(proto_issue);
            } else {
                warnings.push(proto_issue);
            }
        }

        let summary = Some(ValidationSummary {
            error_count: errors.len() as i32,
            warning_count: warnings.len() as i32,
            info_count: 0,
        });

        Ok(Response::new(ValidateResponse {
            valid,
            errors,
            warnings,
            summary,
            validation_report: Some(proto_validation_report_from_rust(&report)),
            validation_report_v2: (req.report_schema_version == 2).then(|| {
                let profile_identity = Some(hl7v2::ValidationReportProfileIdentity {
                    label: profile.message_structure.clone(),
                    message_structure: Some(profile.message_structure.clone()),
                    version: Some(profile.version.clone()),
                    sha256: None,
                });
                proto_validation_report_v2_from_rust(&report.to_v2(
                    "hl7v2-server-grpc",
                    env!("CARGO_PKG_VERSION"),
                    profile_identity,
                ))
            }),
        }))
    }

    async fn validate_redacted(
        &self,
        request: Request<ValidateRedactedRequest>,
    ) -> Result<Response<ValidateRedactedResponse>, Status> {
        let req = request.into_inner();
        let report_schema_version =
            grpc_requested_schema_version(req.report_schema_version, "validation report")
                .map_err(Status::invalid_argument)?;
        let redaction_receipt_schema_version = grpc_requested_schema_version(
            req.redaction_receipt_schema_version,
            "redaction receipt",
        )
        .map_err(Status::invalid_argument)?;

        let message_bytes = if req.mllp_framed {
            hl7v2::unwrap_mllp(&req.message)
                .map_err(|e| Status::invalid_argument(format!("Failed to unwrap MLLP: {e}")))?
        } else {
            req.message.as_slice()
        };

        let mut message = rust_parse(message_bytes)
            .map_err(|e| Status::invalid_argument(format!("Failed to parse HL7: {e}")))?;

        let receipt = redact_message(&mut message, &req.redaction_policy)
            .map_err(|e| Status::invalid_argument(format!("Failed to redact HL7: {e}")))?;
        let redacted_hl7 = hl7v2::write(&message);

        let profile = hl7v2::load_profile_checked(&req.profile)
            .map_err(|_error| Status::invalid_argument(crate::PROFILE_LOAD_SAFE_MESSAGE))?;

        let issues = hl7v2::validate(&message, &profile);
        let report = hl7v2::ValidationReport::from_issues(
            &message,
            Some(profile.message_structure.clone()),
            issues,
        );

        let validation_report_v2 = (report_schema_version == 2).then(|| {
            let profile_identity = Some(hl7v2::ValidationReportProfileIdentity {
                label: profile.message_structure.clone(),
                message_structure: Some(profile.message_structure.clone()),
                version: Some(profile.version.clone()),
                sha256: Some(compute_sha256(&req.profile)),
            });
            proto_validation_report_v2_from_rust(&report.to_v2(
                "hl7v2-server-grpc",
                env!("CARGO_PKG_VERSION"),
                profile_identity,
            ))
        });

        let redaction_receipt_v2 = (redaction_receipt_schema_version == 2)
            .then(|| proto_redaction_receipt_v2_from_server(&receipt, "hl7v2-server-grpc"));

        Ok(Response::new(ValidateRedactedResponse {
            validation_report: Some(proto_validation_report_from_rust(&report)),
            validation_report_v2,
            redaction_receipt: Some(proto_redaction_receipt_from_server(&receipt)),
            redaction_receipt_v2,
            redacted_hl7: req.include_redacted_hl7.then_some(redacted_hl7),
        }))
    }

    async fn corpus_summarize(
        &self,
        request: Request<CorpusSummarizeRequest>,
    ) -> Result<Response<CorpusSummarizeResponse>, Status> {
        let req = request.into_inner();
        let summary_schema_version =
            grpc_requested_schema_version(req.summary_schema_version, "corpus summary")
                .map_err(Status::invalid_argument)?;
        let ids =
            validated_grpc_corpus_message_ids(&req.messages).map_err(Status::invalid_argument)?;
        let messages = grpc_corpus_message_refs(&req.messages, &ids);
        let summary =
            hl7v2::synthetic::corpus::summarize_corpus_messages("<inline-corpus>", &messages);
        let summary_v2 = (summary_schema_version == 2).then(|| {
            proto_corpus_summary_v2_from_rust(
                &summary.to_v2("hl7v2-server-grpc", env!("CARGO_PKG_VERSION")),
            )
        });

        Ok(Response::new(CorpusSummarizeResponse {
            summary: Some(proto_corpus_summary_from_rust(&summary)),
            summary_v2,
        }))
    }

    async fn corpus_fingerprint(
        &self,
        request: Request<CorpusFingerprintRequest>,
    ) -> Result<Response<CorpusFingerprintResponse>, Status> {
        let req = request.into_inner();
        let fingerprint_schema_version =
            grpc_requested_schema_version(req.fingerprint_schema_version, "corpus fingerprint")
                .map_err(Status::invalid_argument)?;
        let ids =
            validated_grpc_corpus_message_ids(&req.messages).map_err(Status::invalid_argument)?;
        let messages = grpc_corpus_message_refs(&req.messages, &ids);
        let mut fingerprint =
            hl7v2::synthetic::corpus::fingerprint_corpus_messages("<inline-corpus>", &messages);

        if let Some(profile_yaml) = req.profile.as_deref() {
            attach_grpc_profile_to_fingerprint(&mut fingerprint, profile_yaml, &req.messages)
                .map_err(Status::invalid_argument)?;
        }

        let fingerprint_v2 = (fingerprint_schema_version == 2).then(|| {
            proto_corpus_fingerprint_v2_from_rust(&fingerprint.to_v2("hl7v2-server-grpc"))
        });

        Ok(Response::new(CorpusFingerprintResponse {
            fingerprint: Some(proto_corpus_fingerprint_from_rust(&fingerprint)),
            fingerprint_v2,
        }))
    }

    async fn corpus_diff(
        &self,
        request: Request<CorpusDiffRequest>,
    ) -> Result<Response<CorpusDiffResponse>, Status> {
        let req = request.into_inner();
        let diff_schema_version =
            grpc_requested_schema_version(req.diff_schema_version, "corpus diff")
                .map_err(Status::invalid_argument)?;
        let before_ids =
            validated_grpc_corpus_message_ids(&req.before).map_err(Status::invalid_argument)?;
        let after_ids =
            validated_grpc_corpus_message_ids(&req.after).map_err(Status::invalid_argument)?;
        let before_messages = grpc_corpus_message_refs(&req.before, &before_ids);
        let after_messages = grpc_corpus_message_refs(&req.after, &after_ids);
        let mut before_fingerprint = hl7v2::synthetic::corpus::fingerprint_corpus_messages(
            "<inline-before>",
            &before_messages,
        );
        let mut after_fingerprint = hl7v2::synthetic::corpus::fingerprint_corpus_messages(
            "<inline-after>",
            &after_messages,
        );

        if let Some(profile_yaml) = req.profile.as_deref() {
            let (profile, profile_metadata) =
                load_grpc_fingerprint_profile(profile_yaml).map_err(Status::invalid_argument)?;
            before_fingerprint.profile = Some(profile_metadata.clone());
            after_fingerprint.profile = Some(profile_metadata);
            before_fingerprint.validation_issue_code_counts =
                grpc_validation_issue_counts_for_loaded_profile(&req.before, &profile);
            after_fingerprint.validation_issue_code_counts =
                grpc_validation_issue_counts_for_loaded_profile(&req.after, &profile);
        }

        let diff = hl7v2::synthetic::corpus::diff_corpus_fingerprints(
            &before_fingerprint,
            &after_fingerprint,
        );
        let diff_v2 = (diff_schema_version == 2)
            .then(|| proto_corpus_diff_report_v2_from_rust(&diff.to_v2("hl7v2-server-grpc")));

        Ok(Response::new(CorpusDiffResponse {
            diff: Some(proto_corpus_diff_report_from_rust(&diff)),
            diff_v2,
        }))
    }

    async fn generate_ack(
        &self,
        request: Request<GenerateAckRequest>,
    ) -> Result<Response<GenerateAckResponse>, Status> {
        let req = request.into_inner();

        let message = rust_parse(&req.message)
            .map_err(|e| Status::invalid_argument(format!("Failed to parse HL7: {}", e)))?;

        let ack_code = match req.code() {
            generate_ack_request::AckCode::Aa => hl7v2::AckCode::AA,
            generate_ack_request::AckCode::Ae => hl7v2::AckCode::AE,
            generate_ack_request::AckCode::Ar => hl7v2::AckCode::AR,
            _ => hl7v2::AckCode::AA,
        };

        let ack_msg = hl7v2::ack(&message, ack_code)
            .map_err(|e| Status::internal(format!("Failed to generate ACK: {}", e)))?;
        let ack_bytes = hl7v2::write(&ack_msg);
        let proto_ack = proto::Message::from(ack_msg);

        Ok(Response::new(GenerateAckResponse {
            ack_message: ack_bytes,
            parsed_ack: Some(proto_ack),
        }))
    }

    async fn normalize(
        &self,
        request: Request<NormalizeRequest>,
    ) -> Result<Response<NormalizeResponse>, Status> {
        let req = request.into_inner();
        let canonical = req
            .options
            .as_ref()
            .map(|o| o.canonical_delimiters)
            .unwrap_or(true);

        let normalized_bytes = hl7v2::normalize(&req.message, canonical)
            .map_err(|e| Status::invalid_argument(format!("Failed to normalize HL7: {}", e)))?;

        let mut final_bytes = normalized_bytes;
        if let Some(options) = req.options
            && options.mllp_frame
        {
            final_bytes = hl7v2::wrap_mllp(&final_bytes);
        }

        Ok(Response::new(NormalizeResponse {
            normalized: final_bytes,
        }))
    }

    async fn health_check(
        &self,
        _request: Request<HealthCheckRequest>,
    ) -> Result<Response<HealthCheckResponse>, Status> {
        let response = HealthCheckResponse {
            status: health_check_response::ServingStatus::Serving as i32,
            version: env!("CARGO_PKG_VERSION").to_string(),
            uptime_seconds: 0,
        };
        Ok(Response::new(response))
    }
}

// ============================================================================
// Conversions
// ============================================================================

fn parse_grpc_message_response(message: &[u8], mllp_framed: bool) -> ParseResponse {
    let parse_result = if mllp_framed {
        match hl7v2::unwrap_mllp(message) {
            Ok(hl7) => rust_parse(hl7),
            Err(e) => {
                return ParseResponse {
                    success: false,
                    message: None,
                    errors: vec![Error {
                        code: "MLLP_ERROR".to_string(),
                        message: format!("Failed to unwrap MLLP: {}", e),
                        details: std::collections::HashMap::new(),
                        trace_id: String::new(),
                    }],
                    metadata: None,
                };
            }
        }
    } else {
        rust_parse(message)
    };

    match parse_result {
        Ok(msg) => {
            let metadata = extract_grpc_metadata(&msg);
            let proto_msg = proto::Message::from(msg);

            ParseResponse {
                success: true,
                message: Some(proto_msg),
                errors: Vec::new(),
                metadata: Some(metadata),
            }
        }
        Err(e) => ParseResponse {
            success: false,
            message: None,
            errors: vec![Error {
                code: "PARSE_ERROR".to_string(),
                message: format!("Failed to parse HL7: {}", e),
                details: std::collections::HashMap::new(),
                trace_id: String::new(),
            }],
            metadata: None,
        },
    }
}

fn parse_stream_response_from_parse_response(response: ParseResponse) -> ParseStreamResponse {
    ParseStreamResponse {
        success: response.success,
        message: response.message,
        errors: response.errors,
        metadata: response.metadata,
    }
}

fn grpc_requested_schema_version(version: i32, artifact: &str) -> Result<i32, String> {
    match version {
        0 | 1 => Ok(1),
        2 => Ok(2),
        other => Err(format!(
            "unsupported {artifact} schema version {other}; expected 1 or 2"
        )),
    }
}

fn compute_sha256(input: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn validated_grpc_corpus_message_ids(
    messages: &[CorpusMessageInput],
) -> Result<Vec<String>, &'static str> {
    if messages.is_empty() {
        return Err("messages must contain at least one message");
    }

    messages
        .iter()
        .enumerate()
        .map(|(index, message)| {
            let label = message
                .id
                .clone()
                .unwrap_or_else(|| format!("message-{}", index.saturating_add(1)));
            validate_grpc_corpus_message_id(&label)?;
            Ok(label)
        })
        .collect()
}

fn validate_grpc_corpus_message_id(label: &str) -> Result<(), &'static str> {
    if label.is_empty() || label == "." || label == ".." || label.len() > 128 {
        return Err("corpus message id must be 1-128 characters and cannot be '.' or '..'");
    }

    if !label
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || matches!(character, '.' | '_' | '-'))
    {
        return Err("corpus message id must use only ASCII letters, numbers, '.', '_' or '-'");
    }

    Ok(())
}

fn grpc_corpus_message_refs<'a>(
    messages: &'a [CorpusMessageInput],
    ids: &'a [String],
) -> Vec<hl7v2::synthetic::corpus::CorpusMessageRef<'a>> {
    messages
        .iter()
        .zip(ids.iter())
        .map(|(message, id)| {
            hl7v2::synthetic::corpus::CorpusMessageRef::new(id.as_str(), message.message.as_slice())
        })
        .collect()
}

fn attach_grpc_profile_to_fingerprint(
    fingerprint: &mut hl7v2::synthetic::corpus::CorpusFingerprint,
    profile_yaml: &str,
    messages: &[CorpusMessageInput],
) -> Result<hl7v2::synthetic::corpus::CorpusFingerprintProfile, &'static str> {
    let (profile, metadata) = load_grpc_fingerprint_profile(profile_yaml)?;
    fingerprint.profile = Some(metadata.clone());
    fingerprint.validation_issue_code_counts =
        grpc_validation_issue_counts_for_loaded_profile(messages, &profile);
    Ok(metadata)
}

fn load_grpc_fingerprint_profile(
    profile_yaml: &str,
) -> Result<
    (
        hl7v2::Profile,
        hl7v2::synthetic::corpus::CorpusFingerprintProfile,
    ),
    &'static str,
> {
    let profile = hl7v2::load_profile_checked(profile_yaml)
        .map_err(|_error| crate::PROFILE_LOAD_SAFE_MESSAGE)?;
    let metadata = hl7v2::synthetic::corpus::CorpusFingerprintProfile {
        path: "<inline-profile>".to_string(),
        sha256: compute_sha256(profile_yaml),
        version: profile.version.clone(),
        message_structure: profile.message_structure.clone(),
    };
    Ok((profile, metadata))
}

fn grpc_validation_issue_counts_for_loaded_profile(
    messages: &[CorpusMessageInput],
    profile: &hl7v2::Profile,
) -> Vec<hl7v2::synthetic::corpus::CorpusCount> {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();

    for message in messages {
        let parsed = if hl7v2::is_mllp_framed(message.message.as_slice()) {
            hl7v2::parse_mllp(message.message.as_slice())
        } else {
            hl7v2::parse(message.message.as_slice())
        };
        let Ok(parsed) = parsed else {
            continue;
        };

        let issues = hl7v2::validate(&parsed, profile);
        let report = hl7v2::ValidationReport::from_issues(
            &parsed,
            Some(profile.message_structure.clone()),
            issues,
        );
        for issue in report.issues {
            let count = counts.entry(issue.code).or_insert(0);
            *count = count.saturating_add(1);
        }
    }

    counts
        .into_iter()
        .map(|(value, count)| hl7v2::synthetic::corpus::CorpusCount { value, count })
        .collect()
}

fn extract_grpc_metadata(msg: &RustMessage) -> MessageMetadata {
    MessageMetadata {
        message_type: joined_components(msg, "MSH.9").unwrap_or_else(|| "UNKNOWN".to_string()),
        version: hl7v2::get(msg, "MSH.12").unwrap_or("UNKNOWN").to_string(),
        control_id: hl7v2::get(msg, "MSH.10").unwrap_or("UNKNOWN").to_string(),
        sending_facility: hl7v2::get(msg, "MSH.4").unwrap_or("").to_string(),
        receiving_facility: hl7v2::get(msg, "MSH.6").unwrap_or("").to_string(),
    }
}

fn proto_corpus_summary_from_rust(
    summary: &hl7v2::synthetic::corpus::CorpusSummary,
) -> CorpusSummary {
    CorpusSummary {
        root: summary.root.clone(),
        file_count: usize_to_u32(summary.file_count),
        message_count: usize_to_u32(summary.message_count),
        parse_error_count: usize_to_u32(summary.parse_error_count),
        total_bytes: usize_to_u64(summary.total_bytes),
        message_types: summary
            .message_types
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        segments: summary
            .segments
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        field_presence: summary
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_from_rust)
            .collect(),
        parse_errors: summary
            .parse_errors
            .iter()
            .map(proto_corpus_parse_failure_from_rust)
            .collect(),
    }
}

fn proto_corpus_summary_v2_from_rust(
    summary: &hl7v2::synthetic::corpus::CorpusSummaryV2,
) -> CorpusSummaryV2 {
    CorpusSummaryV2 {
        schema_version: summary.schema_version.clone(),
        tool_name: summary.tool_name.clone(),
        tool_version: summary.tool_version.clone(),
        root: summary.summary.root.clone(),
        file_count: usize_to_u32(summary.summary.file_count),
        message_count: usize_to_u32(summary.summary.message_count),
        parse_error_count: usize_to_u32(summary.summary.parse_error_count),
        total_bytes: usize_to_u64(summary.summary.total_bytes),
        message_types: summary
            .summary
            .message_types
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        segments: summary
            .summary
            .segments
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        field_presence: summary
            .summary
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_from_rust)
            .collect(),
        parse_errors: summary
            .summary
            .parse_errors
            .iter()
            .map(proto_corpus_parse_failure_from_rust)
            .collect(),
    }
}

fn proto_corpus_count_from_rust(count: &hl7v2::synthetic::corpus::CorpusCount) -> CorpusCount {
    CorpusCount {
        value: count.value.clone(),
        count: usize_to_u32(count.count),
    }
}

fn proto_corpus_field_presence_from_rust(
    field: &hl7v2::synthetic::corpus::CorpusFieldPresence,
) -> CorpusFieldPresence {
    CorpusFieldPresence {
        path: field.path.clone(),
        message_count: usize_to_u32(field.message_count),
        occurrence_count: usize_to_u32(field.occurrence_count),
    }
}

fn proto_corpus_parse_failure_from_rust(
    failure: &hl7v2::synthetic::corpus::CorpusParseFailure,
) -> CorpusParseFailure {
    CorpusParseFailure {
        path: failure.path.clone(),
        error: failure.error.clone(),
    }
}

fn proto_corpus_fingerprint_from_rust(
    fingerprint: &hl7v2::synthetic::corpus::CorpusFingerprint,
) -> CorpusFingerprint {
    CorpusFingerprint {
        fingerprint_version: fingerprint.fingerprint_version.clone(),
        tool_version: fingerprint.tool_version.clone(),
        root: fingerprint.root.clone(),
        profile: fingerprint
            .profile
            .as_ref()
            .map(proto_corpus_fingerprint_profile_from_rust),
        file_count: usize_to_u32(fingerprint.file_count),
        message_count: usize_to_u32(fingerprint.message_count),
        parse_error_count: usize_to_u32(fingerprint.parse_error_count),
        message_type_counts: fingerprint
            .message_type_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        segment_counts: fingerprint
            .segment_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        field_presence: fingerprint
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_from_rust)
            .collect(),
        field_cardinality: fingerprint
            .field_cardinality
            .iter()
            .map(proto_corpus_field_cardinality_from_rust)
            .collect(),
        value_shape_stats: fingerprint
            .value_shape_stats
            .iter()
            .map(proto_corpus_value_shape_stats_from_rust)
            .collect(),
        validation_issue_code_counts: fingerprint
            .validation_issue_code_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
    }
}

fn proto_corpus_fingerprint_v2_from_rust(
    fingerprint: &hl7v2::synthetic::corpus::CorpusFingerprintV2,
) -> CorpusFingerprintV2 {
    let report = &fingerprint.fingerprint;
    CorpusFingerprintV2 {
        schema_version: fingerprint.schema_version.clone(),
        tool_name: fingerprint.tool_name.clone(),
        fingerprint_version: report.fingerprint_version.clone(),
        tool_version: report.tool_version.clone(),
        root: report.root.clone(),
        profile: report
            .profile
            .as_ref()
            .map(proto_corpus_fingerprint_profile_from_rust),
        file_count: usize_to_u32(report.file_count),
        message_count: usize_to_u32(report.message_count),
        parse_error_count: usize_to_u32(report.parse_error_count),
        message_type_counts: report
            .message_type_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        segment_counts: report
            .segment_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
        field_presence: report
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_from_rust)
            .collect(),
        field_cardinality: report
            .field_cardinality
            .iter()
            .map(proto_corpus_field_cardinality_from_rust)
            .collect(),
        value_shape_stats: report
            .value_shape_stats
            .iter()
            .map(proto_corpus_value_shape_stats_from_rust)
            .collect(),
        validation_issue_code_counts: report
            .validation_issue_code_counts
            .iter()
            .map(proto_corpus_count_from_rust)
            .collect(),
    }
}

fn proto_corpus_diff_report_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusDiffReport,
) -> CorpusDiffReport {
    CorpusDiffReport {
        diff_version: diff.diff_version.clone(),
        tool_version: diff.tool_version.clone(),
        before_root: diff.before_root.clone(),
        after_root: diff.after_root.clone(),
        profile: diff
            .profile
            .as_ref()
            .map(proto_corpus_fingerprint_profile_from_rust),
        file_count: Some(proto_corpus_total_diff_from_rust(&diff.file_count)),
        message_count: Some(proto_corpus_total_diff_from_rust(&diff.message_count)),
        parse_error_count: Some(proto_corpus_total_diff_from_rust(&diff.parse_error_count)),
        new_message_types: diff.new_message_types.clone(),
        removed_message_types: diff.removed_message_types.clone(),
        new_segments: diff.new_segments.clone(),
        removed_segments: diff.removed_segments.clone(),
        message_type_counts: diff
            .message_type_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
        segment_counts: diff
            .segment_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
        field_presence: diff
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_diff_from_rust)
            .collect(),
        field_cardinality: diff
            .field_cardinality
            .iter()
            .map(proto_corpus_field_cardinality_diff_from_rust)
            .collect(),
        value_shape_stats: diff
            .value_shape_stats
            .iter()
            .map(proto_corpus_value_shape_stats_diff_from_rust)
            .collect(),
        validation_issue_code_counts: diff
            .validation_issue_code_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
    }
}

fn proto_corpus_diff_report_v2_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusDiffReportV2,
) -> CorpusDiffReportV2 {
    let report = &diff.report;
    CorpusDiffReportV2 {
        schema_version: diff.schema_version.clone(),
        tool_name: diff.tool_name.clone(),
        diff_version: report.diff_version.clone(),
        tool_version: report.tool_version.clone(),
        before_root: report.before_root.clone(),
        after_root: report.after_root.clone(),
        profile: report
            .profile
            .as_ref()
            .map(proto_corpus_fingerprint_profile_from_rust),
        file_count: Some(proto_corpus_total_diff_from_rust(&report.file_count)),
        message_count: Some(proto_corpus_total_diff_from_rust(&report.message_count)),
        parse_error_count: Some(proto_corpus_total_diff_from_rust(&report.parse_error_count)),
        new_message_types: report.new_message_types.clone(),
        removed_message_types: report.removed_message_types.clone(),
        new_segments: report.new_segments.clone(),
        removed_segments: report.removed_segments.clone(),
        message_type_counts: report
            .message_type_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
        segment_counts: report
            .segment_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
        field_presence: report
            .field_presence
            .iter()
            .map(proto_corpus_field_presence_diff_from_rust)
            .collect(),
        field_cardinality: report
            .field_cardinality
            .iter()
            .map(proto_corpus_field_cardinality_diff_from_rust)
            .collect(),
        value_shape_stats: report
            .value_shape_stats
            .iter()
            .map(proto_corpus_value_shape_stats_diff_from_rust)
            .collect(),
        validation_issue_code_counts: report
            .validation_issue_code_counts
            .iter()
            .map(proto_corpus_count_diff_from_rust)
            .collect(),
    }
}

fn proto_corpus_fingerprint_profile_from_rust(
    profile: &hl7v2::synthetic::corpus::CorpusFingerprintProfile,
) -> CorpusFingerprintProfile {
    CorpusFingerprintProfile {
        path: profile.path.clone(),
        sha256: profile.sha256.clone(),
        version: profile.version.clone(),
        message_structure: profile.message_structure.clone(),
    }
}

fn proto_corpus_total_diff_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusTotalDiff,
) -> CorpusTotalDiff {
    CorpusTotalDiff {
        before: usize_to_u64(diff.before),
        after: usize_to_u64(diff.after),
        delta: i128_to_i64(diff.delta),
    }
}

fn proto_corpus_count_diff_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusCountDiff,
) -> CorpusCountDiff {
    CorpusCountDiff {
        value: diff.value.clone(),
        before: usize_to_u64(diff.before),
        after: usize_to_u64(diff.after),
        delta: i128_to_i64(diff.delta),
    }
}

fn proto_corpus_field_presence_diff_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusFieldPresenceDiff,
) -> CorpusFieldPresenceDiff {
    CorpusFieldPresenceDiff {
        path: diff.path.clone(),
        before_message_count: usize_to_u64(diff.before_message_count),
        after_message_count: usize_to_u64(diff.after_message_count),
        message_count_delta: i128_to_i64(diff.message_count_delta),
        before_occurrence_count: usize_to_u64(diff.before_occurrence_count),
        after_occurrence_count: usize_to_u64(diff.after_occurrence_count),
        occurrence_count_delta: i128_to_i64(diff.occurrence_count_delta),
    }
}

fn proto_corpus_field_cardinality_diff_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusFieldCardinalityDiff,
) -> CorpusFieldCardinalityDiff {
    CorpusFieldCardinalityDiff {
        path: diff.path.clone(),
        before_min_per_message: usize_to_u64(diff.before_min_per_message),
        after_min_per_message: usize_to_u64(diff.after_min_per_message),
        min_per_message_delta: i128_to_i64(diff.min_per_message_delta),
        before_max_per_message: usize_to_u64(diff.before_max_per_message),
        after_max_per_message: usize_to_u64(diff.after_max_per_message),
        max_per_message_delta: i128_to_i64(diff.max_per_message_delta),
        before_total_occurrences: usize_to_u64(diff.before_total_occurrences),
        after_total_occurrences: usize_to_u64(diff.after_total_occurrences),
        total_occurrences_delta: i128_to_i64(diff.total_occurrences_delta),
        before_message_count: usize_to_u64(diff.before_message_count),
        after_message_count: usize_to_u64(diff.after_message_count),
        message_count_delta: i128_to_i64(diff.message_count_delta),
    }
}

fn proto_corpus_value_shape_stats_diff_from_rust(
    diff: &hl7v2::synthetic::corpus::CorpusValueShapeStatsDiff,
) -> CorpusValueShapeStatsDiff {
    CorpusValueShapeStatsDiff {
        path: diff.path.clone(),
        coded_count: Some(proto_corpus_total_diff_from_rust(&diff.coded_count)),
        timestamp_count: Some(proto_corpus_total_diff_from_rust(&diff.timestamp_count)),
        numeric_count: Some(proto_corpus_total_diff_from_rust(&diff.numeric_count)),
        null_count: Some(proto_corpus_total_diff_from_rust(&diff.null_count)),
        text_count: Some(proto_corpus_total_diff_from_rust(&diff.text_count)),
    }
}

fn proto_corpus_field_cardinality_from_rust(
    field: &hl7v2::synthetic::corpus::CorpusFieldCardinality,
) -> CorpusFieldCardinality {
    CorpusFieldCardinality {
        path: field.path.clone(),
        min_per_message: usize_to_u32(field.min_per_message),
        max_per_message: usize_to_u32(field.max_per_message),
        total_occurrences: usize_to_u32(field.total_occurrences),
        message_count: usize_to_u32(field.message_count),
    }
}

fn proto_corpus_value_shape_stats_from_rust(
    stats: &hl7v2::synthetic::corpus::CorpusValueShapeStats,
) -> CorpusValueShapeStats {
    CorpusValueShapeStats {
        path: stats.path.clone(),
        coded_count: usize_to_u32(stats.coded_count),
        timestamp_count: usize_to_u32(stats.timestamp_count),
        numeric_count: usize_to_u32(stats.numeric_count),
        null_count: usize_to_u32(stats.null_count),
        text_count: usize_to_u32(stats.text_count),
    }
}

fn usize_to_u32(value: usize) -> u32 {
    u32::try_from(value).unwrap_or(u32::MAX)
}

fn usize_to_u64(value: usize) -> u64 {
    u64::try_from(value).unwrap_or(u64::MAX)
}

fn i128_to_i64(value: i128) -> i64 {
    i64::try_from(value).unwrap_or(if value.is_negative() {
        i64::MIN
    } else {
        i64::MAX
    })
}

fn proto_validation_report_from_rust(report: &hl7v2::ValidationReport) -> ValidationReport {
    ValidationReport {
        valid: report.valid,
        message_type: report.message_type.clone(),
        profile: report.profile.clone(),
        segment_count: report.segment_count as i32,
        issue_count: report.issue_count as i32,
        issues: report
            .issues
            .iter()
            .map(proto_validation_report_issue_from_rust)
            .collect(),
    }
}

fn proto_validation_report_v2_from_rust(report: &hl7v2::ValidationReportV2) -> ValidationReportV2 {
    ValidationReportV2 {
        schema_version: report.schema_version.clone(),
        tool_name: report.tool_name.clone(),
        tool_version: report.tool_version.clone(),
        valid: report.valid,
        message_type: report.message_type.clone(),
        profile: report.profile.clone(),
        profile_identity: report
            .profile_identity
            .as_ref()
            .map(proto_validation_report_profile_identity_from_rust),
        segment_count: report.segment_count as i32,
        issue_count: report.issue_count as i32,
        issues: report
            .issues
            .iter()
            .map(proto_validation_report_issue_from_rust)
            .collect(),
    }
}

fn proto_validation_report_profile_identity_from_rust(
    profile: &hl7v2::ValidationReportProfileIdentity,
) -> ValidationReportProfileIdentity {
    ValidationReportProfileIdentity {
        label: profile.label.clone(),
        message_structure: profile.message_structure.clone(),
        version: profile.version.clone(),
        sha256: profile.sha256.clone(),
    }
}

fn proto_validation_report_issue_from_rust(
    issue: &hl7v2::ValidationReportIssue,
) -> ValidationReportIssue {
    ValidationReportIssue {
        code: issue.code.clone(),
        severity: issue.severity.as_str().to_string(),
        path: issue.path.clone(),
        rule_id: issue.rule_id.clone(),
        message: issue.message.clone(),
        segment_index: issue.segment_index.map(|value| value as u32),
        field_index: issue.field_index.map(|value| value as u32),
    }
}

fn proto_redaction_receipt_from_server(receipt: &ServerRedactionReceipt) -> RedactionReceipt {
    RedactionReceipt {
        phi_removed: receipt.phi_removed,
        hash_algorithm: receipt.hash_algorithm.clone(),
        actions: receipt
            .actions
            .iter()
            .map(proto_redaction_action_receipt_from_server)
            .collect(),
    }
}

fn proto_redaction_receipt_v2_from_server(
    receipt: &ServerRedactionReceipt,
    tool_name: &str,
) -> RedactionReceiptV2 {
    RedactionReceiptV2 {
        schema_version: "2".to_string(),
        tool_name: tool_name.to_string(),
        tool_version: env!("CARGO_PKG_VERSION").to_string(),
        phi_removed: receipt.phi_removed,
        hash_algorithm: receipt.hash_algorithm.clone(),
        actions: receipt
            .actions
            .iter()
            .map(proto_redaction_action_receipt_from_server)
            .collect(),
    }
}

fn proto_redaction_action_receipt_from_server(
    action: &ServerRedactionActionReceipt,
) -> RedactionActionReceipt {
    RedactionActionReceipt {
        path: action.path.clone(),
        action: server_redaction_action_name(action.action).to_string(),
        reason: action.reason.clone(),
        matched_count: u32::try_from(action.matched_count).unwrap_or(u32::MAX),
        optional: action.optional,
        status: server_redaction_action_status_name(action.status).to_string(),
    }
}

fn server_redaction_action_name(action: ServerRedactionAction) -> &'static str {
    match action {
        ServerRedactionAction::Hash => "hash",
        ServerRedactionAction::Drop => "drop",
        ServerRedactionAction::Retain => "retain",
    }
}

fn server_redaction_action_status_name(status: ServerRedactionActionStatus) -> &'static str {
    match status {
        ServerRedactionActionStatus::Applied => "applied",
        ServerRedactionActionStatus::Retained => "retained",
        ServerRedactionActionStatus::NotFound => "not_found",
    }
}

fn joined_components(msg: &RustMessage, field_path: &str) -> Option<String> {
    let mut components = Vec::new();

    for component in 1.. {
        let path = format!("{field_path}.{component}");
        match hl7v2::get(msg, &path) {
            Some(value) if !value.is_empty() => components.push(value.to_string()),
            _ if component == 1 => return None,
            _ => break,
        }
    }

    Some(components.join("^"))
}

impl From<RustMessage> for proto::Message {
    fn from(msg: RustMessage) -> Self {
        proto::Message {
            delimiters: Some(proto::Delimiters {
                field: msg.delims.field.to_string(),
                component: msg.delims.comp.to_string(),
                repetition: msg.delims.rep.to_string(),
                escape: msg.delims.esc.to_string(),
                subcomponent: msg.delims.sub.to_string(),
            }),
            segments: msg.segments.into_iter().map(Into::into).collect(),
        }
    }
}

impl From<RustSegment> for proto::Segment {
    fn from(seg: RustSegment) -> Self {
        proto::Segment {
            id: String::from_utf8_lossy(&seg.id).to_string(),
            fields: seg.fields.into_iter().map(Into::into).collect(),
            sequence: 0,
        }
    }
}

impl From<RustField> for proto::Field {
    fn from(f: RustField) -> Self {
        let presence = if f.reps.is_empty() {
            proto::field::Presence::Missing as i32
        } else {
            proto::field::Presence::Value as i32
        };

        proto::Field {
            presence,
            value: f.first_text().map(String::from),
            repetitions: f.reps.into_iter().map(Into::into).collect(),
        }
    }
}

impl From<RustRep> for proto::Repetition {
    fn from(r: RustRep) -> Self {
        proto::Repetition {
            value: r.first_text().map(String::from),
            components: r.comps.into_iter().map(Into::into).collect(),
        }
    }
}

impl From<RustComp> for proto::Component {
    fn from(c: RustComp) -> Self {
        proto::Component {
            value: c.first_text().map(String::from),
            subcomponents: c
                .subs
                .into_iter()
                .filter_map(|a| match a {
                    hl7v2::Atom::Text(t) => Some(t),
                    _ => None,
                })
                .collect(),
        }
    }
}
