[package]
name = "hl7v2-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Python bindings for HL7v2 via PyO3."
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "hl7v2"
crate-type = ["cdylib"]
doc = false

[dependencies]
hl7v2 = { version = "1.2.1", path = "../hl7v2", features = [
    "profile",
    "ack",
    "normalize",
    "json",
] }
pyo3 = { version = "0.24.1", features = ["extension-module"] }
serde_json = { workspace = true }
