name: CI

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89
          components: clippy, rustfmt
      - name: Check
        run: cargo check --workspace --all-features
      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets
      - name: Format
        run: cargo fmt --all -- --check

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         toolchain: 1.89
  #     - name: Test
  #       run: cargo test --workspace --all-features
